### ISSUE TITLE
hindent requires a style argument

### ISSUE THREAD

**Issue by pnaranja** [alx741/vim-hindent#1]
Hello,
#### The latest hindent version requires at lease a style argument:

$ hindent
hindent: --version --style (fundamental|chris-done|johan-tibell|gibiansky|cramer) --line-length <...> [-X<...>]\* [<FILENAME>]

$ hindent --version
hindent 4.6.3
#### I've edited the hindent.vim to use johan-tibell for my personal use.

```
silent! silent exec "!cat % | hindent --style johan-tibell"
exec ':redraw!'

if v:shell_error
    echom "Hindent: Parsing error"
else
    silent! exec "%!hindent --style johan-tibell"
endif
```

I guess you could just choose a default style and allow the user to choose in their .vimrc

**Comment by alx741** [comment]
Hey,

I thought about adding a variable to allow the user to select the style, but then I read latest Cris Done's [blog post](http://chrisdone.com/posts/hindent-5) and apparently since version 5.x _hindent_ silently ignores style arguments and only uses Tibell's style.

So if you update _hindent_ now you'll be using `johan-tibell` as the default and only style.

**Comment by pnaranja** [comment]
Thanks for the info.  I just updated to hindent 5.2.1 and I see it default with `johan-tibell`.
Right now, `stack install hindent` only provides version 4.6.3.
